### PR TITLE
request to fork project.

### PR DESCRIPTION
**Pull request by Aki-98**
please confirm the files changed, 

thanks for reviewing

### CODE REVIEW

**Comment by Maikaru-Sensei** [comment]
Hi Aki!

Thanks for the interest in my project, it was such a long time ago.

You are free to do anything you want with my source code. Commercial use included :)

If you want we could start the project all over together. Just create a new project and invite me as a collaborator but its your choice you don't have to.

Michael

**Comment by Aki-98** [comment]
> Hi Aki!
> 
> Thanks for the interest in my project, it was such a long time ago.
> 
> You are free to do anything you want with my source code. Commercial use included :)
> 
> If you want we could start the project all over together. Just create a new project and invite me as a collaborator but its your choice you don't have to.
> 
> Michael

Hi, Michael :)

After sharing this project idea with people around me and in online communities, some have shown great interest and are willing to join us. We believe this project has the potential to develop into a cross-platform solution.

My friend **ioio** suggested creating a browser extension to integrate account and password management between browsers and mobile devices. Additionally, ioio is willing to handle cross-platform data transmission, enabling devices to share data through local hotspot networks. 

ioio is a freelance developer with broad technical knowledge, a wide vision, and a strong passion for free software.

Another friend, **Victor**, is willing to work on the password generation solution and provide advice on cryptography and attack prevention. 

Victor is a PhD in computer science, currently focusing on audio algorithm research.

Although the project is cross-platform, we hope to keep data transmission local (via Bluetooth or LAN), as maintaining a backend is highly uncontrollable and costly. Relying on funding to sustain operations could easily deviate from the original free software philosophy.

We plan to bring in more contributors, with each developer focusing on a major aspect of the project. However, since the project is still in the solution exploration phase, specific roles have not yet been determined. Also, we are in different time zones, and English is not our native language. While we can read and write in English, our proficiency levels vary, which may cause some challenges in collaboration and communication.

If you are willing to accept these challenges and are still interested in our project, please provide your contact information for **Element**, and we can create a discussion group for further collaboration.

I noticed you have experience with Flutter. What kind of support can Flutter provide for our application? Can it fully meet the needs of cross-platform development, or does it require integration with native code? It would be best to discuss this topic further in the discussion group so that others can be informed as well.

Aki

**Comment by Maikaru-Sensei** [comment]
Hi,

Flutter is very suitable for your project. I am working as a Flutter dev currently.

Flutter has its drawback when it comes to hardware access but nowadays the framework is really stable.

Element: @maikaru:matrix.org

**Comment by Aki-98** [comment]
> Hi,
> 
> Flutter is very suitable for your project. I am working as a Flutter dev currently.
> 
> Flutter has its drawback when it comes to hardware access but nowadays the framework is really stable.
> 
> Element: @maikaru:matrix.org

I have already invited you to join the Element discussion group and the GitHub repository. 
We are looking forward to collaborating with you and exchanging ideas.

**Pull request closed without merging**
